---
# tasks file for builder
- name: installing necessary packages on builder
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - default-jdk
    - maven

- name: cloning boxfuse
  git:
    repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
    dest: "{{ workdir }}"
  notify:
     - building project
